name: t3/faq
typeName: t3_faq
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  - 
    identifier: tabs_item
    type: Collection
    label: FAQ Items
    minitems: 1
    
    fields:
      - identifier: question
        type: Text
        label: Question

      - identifier: answer
        type: Textarea
        label: Answer
        enableRichtext: true
